-- AI Tool Stack: Initial Database Schema
-- NOTE: Superseded by 002_aitoolstack_tables.sql
-- This file is kept for reference. Run 002 instead.
-- All tables use the ats_ prefix to avoid conflicts with other projects.
